_wandb:
    value:
        cli_version: 0.23.0
        e:
            nn537nbipiq7qyodamnfjyigzlzp33m6:
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "305402470400"
                        used: "183869739008"
                email: samuelparson122@gmail.com
                executable: /home/sam/Documents/marioRL_3.10/venv/bin/python
                git:
                    commit: 8f73a580440b0e2be6f7bd60e0c2a67cc4e041ec
                    remote: git@github.com:mangoseller/mario_RL.git
                host: sam-B650M-GAMING-WIFI
                memory:
                    total: "32703377408"
                os: Linux-6.14.0-35-generic-x86_64-with-glibc2.39
                program: <python with no main file>
                python: CPython 3.10.19
                root: /home/sam/Documents/marioRL_3.10/src/wandb_search
                startedAt: "2025-11-18T22:37:38.553552Z"
                writerId: nn537nbipiq7qyodamnfjyigzlzp33m6
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 2
                - 14
            "4": 3.10.19
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
c2:
    value: 0.05353557956885608
learning_rate:
    value: 6.031241971536917e-05
