_wandb:
    value:
        cli_version: 0.23.0
        e:
            n1jq1xtodbu4qjwse3tnmizhczuz5hkb:
                email: samuelparson122@gmail.com
                executable: /home/sam/Documents/marioRL_3.10/venv/bin/python
                git:
                    commit: 8f73a580440b0e2be6f7bd60e0c2a67cc4e041ec
                    remote: git@github.com:mangoseller/mario_RL.git
                host: sam-B650M-GAMING-WIFI
                os: Linux-6.14.0-35-generic-x86_64-with-glibc2.39
                program: <python with no main file>
                python: CPython 3.10.19
                root: /home/sam/Documents/marioRL_3.10/src/wandb_search
                startedAt: "2025-11-18T22:37:43.962489Z"
                writerId: n1jq1xtodbu4qjwse3tnmizhczuz5hkb
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 2
                - 14
            "4": 3.10.19
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
c2:
    value: 0.09145921086669533
learning_rate:
    value: 0.0003819335503008875
