_wandb:
    value:
        cli_version: 0.23.0
        e:
            xst640etcatm15v07wcc4clem75crdfo:
                codePath: src/wandb_search/run_sweep.py
                codePathLocal: run_sweep.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "305402470400"
                        used: "183959281664"
                email: samuelparson122@gmail.com
                executable: /home/sam/Documents/marioRL_3.10/venv/bin/python
                git:
                    commit: 85e934a6cccbc75a9c3a274fd6e0ee4f87f9eb2f
                    remote: git@github.com:mangoseller/mario_RL.git
                host: sam-B650M-GAMING-WIFI
                memory:
                    total: "32703377408"
                os: Linux-6.14.0-35-generic-x86_64-with-glibc2.39
                program: /home/sam/Documents/marioRL_3.10/src/wandb_search/run_sweep.py
                python: CPython 3.10.19
                root: /home/sam/Documents/marioRL_3.10/src/wandb_search
                startedAt: "2025-11-19T00:10:36.032221Z"
                writerId: xst640etcatm15v07wcc4clem75crdfo
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 14
            "4": 3.10.19
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
c2:
    value: 0.0309287662054326
learning_rate:
    value: 0.00023448840522787023
